name: Email Step Test

# Trigger the workflow on pushes or manual trigger
on:
  push:
    branches: [ main ]   # your default branch
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24ds2000074@ds.study.iitm.ac.in
        run: |
          echo "This step contains my email!"
