name: Test Workflow

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24ds2000074@ds.study.iitm.ac.in
        run: echo "Hello, world!"
